### Produire des commandes sur le topic appro-event
POST http://localhost:8082/topics/appro-event
Content-Type: application/vnd.kafka.json.v2+json
Accept: application/vnd.kafka.v2+json, application/vnd.kafka+json, application/json

{
  "records": [
    {
      "key": "{{$random.alphabetic(5)}}",
      "value": {
        "fournitures": [
          {
            "nom": "{{$random.alphabetic(10)}}",
            "prixHT": {{$random.float(100)}},
            "fournisseur": {
              "nom": "{{$random.alphabetic(15)}}",
              "adresse": "{{$random.alphabetic(20)}}",
              "siret": "{{$random.alphanumeric(14)}}"
            }
          },
          {
            "nom": "{{$random.alphabetic(10)}}",
            "prixHT": {{$random.float(100)}},
            "fournisseur": {
              "nom": "{{$random.alphabetic(15)}}",
              "adresse": "{{$random.alphabetic(20)}}",
              "siret": "{{$random.alphanumeric(14)}}"
            }
          }
        ]
      }
    }
  ]
}